version: "3.2"
services:
  redis:
    restart: always
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - db-net

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db-net

  backend:
    restart: always
    container_name: django
    command : bash -c "python check_db.py --service-name db --ip db --port 5432 && 
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend:/code

    depends_on:
      - db
      - redis
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - db-net

  frontend:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: always
    command : npm start
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge